name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "infra/terraform/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write       # Required for OIDC
      contents: read

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Authenticate with GCP using OIDC (no keys)
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/543604086358/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-sa@dileeppm.iam.gserviceaccount.com"

      # 3️⃣ Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure project
        run: gcloud config set project dileeppm

      # 4️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 5️⃣ Terraform Init
      - name: Terraform Init
        run: terraform -chdir=infra/terraform init

      # 6️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan

      # 7️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=infra/terraform apply -auto-approve

